import Head from "next/head";
import { connectToDatabase } from "../util/mongodb";
import { GetStaticProps } from "next";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>test</h1>
      </main>
    </div>
  );
}

// We can pass the entire object down the tree to map, but this may be bad practice
export const getStaticProps: GetStaticProps = async (context) => {
  const { collection } = await connectToDatabase();

  // Get all content items, must elimate _id to serialize
  // Key will be set within collection entries
  let content = await collection
    .find({}, { projection: { _id: 0 } })
    .toArray()
    .then((items) => {
      return items;
    });
  return {
    props: { content },
  };
};
